project:
  type: website
  output-dir: docs
  
website:
  title: "LightLogR Webinar"
  repo-url: "https://github.com/tscnlab/LightLogR_webinar"
  issue-url: "https://github.com/tscnlab/LightLogR_webinar/issues"
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  # announcement: 
  #   icon: info-circle
  #   dismissable: true
  #   content: "<strong>Final advanced session – 6 May 2026</strong> 
  # <a href='https://eu02web.zoom.us/meeting/register/HVvnEunVTLWr3ei7dwCfZg#/registration' target='_blank'> → Register here</a><br>
  # Covering use cases 3 and 4: multi-modal analysis and intervention comparison.<br>"
  #   type: primary
  #   position: below-navbar
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: "Course flyer"
        href: assets/Online_course_series_2025-26.pdf
        target: "_blank"
      - text: "Register"
        href: https://eu02web.zoom-x.de/meeting/register/HVvnEunVTLWr3ei7dwCfZg
        target: "_blank"
      - text: "Recordings"
        href: recordings.qmd
      - text: "Slides"
        href: assets/2025.10.07_LightLogR.pdf
        target: "_blank"
      - text: Beginner
        menu:
        - text: Beginner (live)
          href: beginner-live.qmd
        - text: Beginner (static)
          href: beginner.qmd
        - text: ---
        - text: Tropical light exposure & health (live)
          href: tropical_light_exposure_health-live.qmd
        - text: Tropical light exposure & health (static)
          href: tropical_light_exposure_health.qmd
      - text: Advanced
        menu:
        - text: A Day in Daylight 
        - text: live
          href: advanced_01_a_day_in_daylight-live.qmd
        - text: static
          href: advanced_01_a_day_in_daylight.qmd
        - text: ---
        - text: Case of high light sensitivity
        - text: live
          href: advanced_02_case_light_sensitivity-live.qmd
        - text: static
          href: advanced_02_case_light_sensitivity.qmd
        - text: ---
        - text: Therapy lamps
        - text: live
          href: advanced_03_light_therapy-live.qmd
        - text: static
          href: advanced_03_light_therapy.qmd
        - text: ---
        - text: "Visual experience: beyond light"
        - text: live
          href: advanced_04_visual_experience-live.qmd
        - text: static
          href: advanced_04_visual_experience.qmd
        - text: ---
      - text: "About / Funding"
        href: about.qmd
      - text: "License"
        href: license.qmd
    right:
      - icon: github
        href: https://github.com/tscnlab/LightLogR_webinar
        aria-label: Quarto GitHub
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto

language:
  title-block-published: "Last modified:"
