project:
  type: website
  output-dir: docs
  
website:
  title: "LightLogR Webinar"
  repo-url: https://github.com/tscnlab/LightLogR_webinar
  issue-url: https://github.com/tscnlab/LightLogR_webinar/issues
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: "Course flyer"
        href: assets/Online_course_series_2025-26.pdf
        target: "_blank"
      - text: "Register"
        href: https://tum-conf.zoom.us/webinar/register/WN_xGoHi1i_Sz2flC6-qGcLoQ#/registration
        target: "_blank"
      - text: "Slides"
        href: assets/2025.10.07_LightLogR.pdf
        target: "_blank"
      - text: Beginner
        menu:
        - text: Beginner (live)
          href: beginner-live.qmd
        - text: Beginner (static)
          href: beginner.qmd
      - text: Advanced
        menu:
        - text: To come soon
      - text: "About / Funding"
        href: about.qmd
      - text: "License"
        href: license.qmd
    right:
      - icon: github
        href: https://github.com/tscnlab/LightLogR_webinar
        aria-label: Quarto GitHub
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto

language:
  title-block-published: "Last modified:"
