{
  "hash": "8a9da5d874bad7f1682fa3a7ad426609",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Use case #03: Light therapy\"\nsubtitle: \"Open and reproducible analysis of light exposure and visual experience data (Advanced)\"\nauthor: \n  - name: \"Johannes Zauner\"\n    affiliation: \"Technical University of Munich & Max Planck Institute for Biological Cybernetics, Germany\"\n    orcid: \"0000-0003-2171-4566\"\nlightbox: true\ncode-tools: true\ncode-link: true\ncode-annotations: below\ncode-line-numbers: true\ndate: last-modified\nnumber-sections: true\n---\n\n\n::: {.cell}\n\n:::\n\n\n## Preface\n\nThis use case covers an exploratory protocol to capture the effect of a light therapy intervention on personal light exposure. Two participants sit in an office environment, one with, one without a therapy lamp on their respective desk. They follow a typical office workflow. The blinds are shut to reduce the directional (and thus differential) effect of daylight on participant's light exposure. Artificial lighting is switched on. In the intervention condition the therapy lamp is switched on for one hour. The participants document the start and end times of each protocol phase (pre-light, therapy light, post-light), as well as any deviations from the protocol. \n\n::: {#fig-overview layout-ncol=2}\n\n![Therapy light workplace (therapy light switched off)](assets/advanced/light_therapy_01.jpg) \n\n![Control workplace](assets/advanced/light_therapy_02.jpg)\n\nPhotographs of workplaces (pre-light). Both workplace have the same CCT roomlighting. The different appearance is due to camera whitebalance.\n:::\n\nThe tutorial focuses on\n\n- merging of participant protocol logs with light from a wearable device\n\n- analysis of light exposure dependent on lighting conditions\n\n- dealing with interruptions from the protocol\n\n- advanced plotting & table styling\n\n- working with data < 1 day in `LightLogR`\n\n![Flowchart diagram of the *Light therapy* use case.](assets/advanced/flowcharts/adv_03.png)\n\n## How this page works\n\nThis document contains the script for the online course series as a [Quarto](https://quarto.org) script, which can be executed on a local installation of R. Please ensure that all libraries are installed prior to running the script.\n\nIf you want to test `LightLogR` without installing R or the package, try the [script](advanced_03_light_therapy-live.qmd) version running webR, for a autonymous but slightly reduced version. These versions are indicated as *(live)*, whereas the current version is considered *(static)*, as it is pre-rendered.\n\nTo run this script, we recommend cloning or downloading the [GitHub repository](https://github.com/tscnlab/LightLogR_webinar) ([link to Zip-file](https://github.com/tscnlab/LightLogR_webinar/archive/refs/heads/main.zip)) and running the respective script. You will need to install the required packages. A quick way is to run:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrenv::restore()\n```\n:::\n\n\n::: {.callout-note}\n## If this is your first course tutorial\n\nThis tutorial is considered as **advanced**. Basic functions in the `LightLogR` package as well as general `tidy` workflows are used without dedicated explanation. We recommend working through the [beginner](beginner.qmd) example if you are new to `LightLogR` (note that there is also a [live](beginner-live.qmd) variant).\n:::\n\n\n## Setup\n\nWe start by loading the necessary packages.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(LightLogR) # main package\nlibrary(tidyverse) # for tidy data science\nlibrary(gt) # for great tables\nlibrary(legendry) # for advanced legend manipulation\nlibrary(readxl) # to read in Excel files\nlibrary(ggridges) # for stacked plots within a panel\nlibrary(ggimage) # to add images to plots\n```\n:::\n\n\n## Import\n\nWe require both light and log data to be loaded into R before we are able to merge them.\n\n### Light\n\nLight data were captured with `ActLumus` devices. The exported data files sit in `data/light_therapy/`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npath <- \"data/light_therapy\"\nfiles <- list.files(path, pattern = \".txt$\", full.names = TRUE)\npattern <- \"Log_(.{4})_\" #<1>\ntz <- \"Europe/Berlin\"\ndata <- import$ActLumus(files, tz = tz, auto.id = pattern)\n```\n\n::: {.cell-output-display}\n![](advanced_03_light_therapy_files/figure-html/import light-1.png){width=480}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSuccessfully read in 318 observations across 2 Ids from 2 ActLumus-file(s).\nTimezone set is Europe/Berlin.\n\nFirst Observation: 2025-10-30 09:46:36\nLast Observation: 2025-10-30 12:26:50\nTimespan: 2.7 hours\n\nObservation intervals: \n  Id    interval.time        n pct  \n1 4789  60s (~1 minutes)   160 100% \n2 5541  60s (~1 minutes)   156 100% \n```\n\n\n:::\n:::\n\n\n1. Pattern to extract Id's from file names\n\nWe can see that it is a small dataset. If we visualize it we can see both participants measured simultaneously in the morning.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoordinates <- c(48.1371, 11.5754) #data were captured in Munich, Germany\ndata |> \n  gg_day(aes_col = fct_rev(Id)) |> \n  gg_photoperiod(coordinates)\n```\n\n::: {.cell-output-display}\n![](advanced_03_light_therapy_files/figure-html/viz light-1.png){width=768}\n:::\n:::\n\n\nParticipant `5541` received the `therapy light`, and `4789` is the `control condition`.\n\nWhile the import summary did not show indications of gaps or irregular data, it always pays to check this.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |> \n  gap_table(full.days = FALSE) |> #<1>\n  cols_hide(contains(\"_n\")) #<2>\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xgahmemtnk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xgahmemtnk table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xgahmemtnk thead, #xgahmemtnk tbody, #xgahmemtnk tfoot, #xgahmemtnk tr, #xgahmemtnk td, #xgahmemtnk th {\n  border-style: none;\n}\n\n#xgahmemtnk p {\n  margin: 0;\n  padding: 0;\n}\n\n#xgahmemtnk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xgahmemtnk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xgahmemtnk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xgahmemtnk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xgahmemtnk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xgahmemtnk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xgahmemtnk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xgahmemtnk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xgahmemtnk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xgahmemtnk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xgahmemtnk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xgahmemtnk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xgahmemtnk .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xgahmemtnk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xgahmemtnk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xgahmemtnk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xgahmemtnk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xgahmemtnk .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xgahmemtnk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xgahmemtnk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xgahmemtnk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xgahmemtnk .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xgahmemtnk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xgahmemtnk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xgahmemtnk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xgahmemtnk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xgahmemtnk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xgahmemtnk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xgahmemtnk .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xgahmemtnk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xgahmemtnk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xgahmemtnk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xgahmemtnk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xgahmemtnk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xgahmemtnk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xgahmemtnk .gt_left {\n  text-align: left;\n}\n\n#xgahmemtnk .gt_center {\n  text-align: center;\n}\n\n#xgahmemtnk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xgahmemtnk .gt_font_normal {\n  font-weight: normal;\n}\n\n#xgahmemtnk .gt_font_bold {\n  font-weight: bold;\n}\n\n#xgahmemtnk .gt_font_italic {\n  font-style: italic;\n}\n\n#xgahmemtnk .gt_super {\n  font-size: 65%;\n}\n\n#xgahmemtnk .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xgahmemtnk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xgahmemtnk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xgahmemtnk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xgahmemtnk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xgahmemtnk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xgahmemtnk .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xgahmemtnk .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xgahmemtnk div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"14\" class=\"gt_heading gt_title gt_font_normal\" style>Summary of available and missing data</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"14\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Variable: melanopic EDI</td>\n    </tr>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th rowspan=\"1\" colspan=\"1\" scope=\"col\"></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"5\" style=\"font-weight: bold; font-weight: bold;\" scope=\"colgroup\" id=\"data_spanner\">\n        <div class=\"gt_column_spanner\">Data</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"8\" style=\"font-weight: bold; font-weight: bold;\" scope=\"colgroup\" id=\"missing_spanner\">\n        <div class=\"gt_column_spanner\">Missing</div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" style=\"font-weight: bold;\" scope=\"colgroup\" id=\"Regular\">\n        <div class=\"gt_column_spanner\">Regular</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"irregular_spanner\">\n        <div class=\"gt_column_spanner\">Irregular</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Range\">\n        <div class=\"gt_column_spanner\">Range</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"interval_spanner\">\n        <div class=\"gt_column_spanner\">Interval</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"4\" style=\"font-weight: bold;\" scope=\"colgroup\" id=\"gap_spanner\">\n        <div class=\"gt_column_spanner\">Gaps</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" style=\"font-weight: bold;\" scope=\"colgroup\" id=\"implicit_spanner\">\n        <div class=\"gt_column_spanner\">Implicit</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" style=\"font-weight: bold;\" scope=\"colgroup\" id=\"explicit_spanner\">\n        <div class=\"gt_column_spanner\">Explicit</div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"available_data\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"available_data_pct\">%</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"number_irregulars\">n<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1,2</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"total_duration\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"interval\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"number_gaps\">N</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean_gap_duration\">ø</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"missing_data\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"missing_data_pct\">%</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"missing_implicit\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"missing_implicit_pct\">%</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"missing_explicit\">Time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"missing_explicit_pct\">%</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"grand_summary_stub_1\" scope=\"row\" class=\"gt_row gt_left gt_stub gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\"><span data-qmd-base64=\"KipPdmVyYWxsKio=\"><span class='gt_from_md'><strong>Overall</strong></span></span></th>\n<td headers=\"grand_summary_stub_1 available_data\" class=\"gt_row gt_center gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\">5h 18m</td>\n<td headers=\"grand_summary_stub_1 available_data_pct\" class=\"gt_row gt_right gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\">100.0%<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>3</sup></span></td>\n<td headers=\"grand_summary_stub_1 number_irregulars\" class=\"gt_row gt_right gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5; border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"grand_summary_stub_1 total_duration\" class=\"gt_row gt_center gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5; border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">5h 18m</td>\n<td headers=\"grand_summary_stub_1 interval\" class=\"gt_row gt_center gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5; border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">60</td>\n<td headers=\"grand_summary_stub_1 number_gaps\" class=\"gt_row gt_right gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5; border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"grand_summary_stub_1 mean_gap_duration\" class=\"gt_row gt_right gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\">0s</td>\n<td headers=\"grand_summary_stub_1 missing_data\" class=\"gt_row gt_center gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\">0s</td>\n<td headers=\"grand_summary_stub_1 missing_data_pct\" class=\"gt_row gt_right gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\">0.0%<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>3</sup></span></td>\n<td headers=\"grand_summary_stub_1 missing_implicit\" class=\"gt_row gt_center gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5; border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0s</td>\n<td headers=\"grand_summary_stub_1 missing_implicit_pct\" class=\"gt_row gt_right gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\">0.0%<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>3</sup></span></td>\n<td headers=\"grand_summary_stub_1 missing_explicit\" class=\"gt_row gt_center gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5; border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0s</td>\n<td headers=\"grand_summary_stub_1 missing_explicit_pct\" class=\"gt_row gt_right gt_grand_summary_row gt_grand_summary_row gt_last_grand_summary_row_top\" style=\"background-color: #E5E5E5;\">0.0%<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>3</sup></span></td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"14\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"4789\">4789</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"4789 stub_1_1 available_data\" class=\"gt_row gt_center\">2h 41m</td>\n<td headers=\"4789 stub_1_1 available_data_pct\" class=\"gt_row gt_right\">100.0%</td>\n<td headers=\"4789 stub_1_1 number_irregulars\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"4789 stub_1_1 total_duration\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">2h 41m</td>\n<td headers=\"4789 stub_1_1 interval\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">60s (~1 minutes)</td>\n<td headers=\"4789 stub_1_1 number_gaps\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"4789 stub_1_1 mean_gap_duration\" class=\"gt_row gt_right\">0s</td>\n<td headers=\"4789 stub_1_1 missing_data\" class=\"gt_row gt_center\">0s</td>\n<td headers=\"4789 stub_1_1 missing_data_pct\" class=\"gt_row gt_right\">0.0%</td>\n<td headers=\"4789 stub_1_1 missing_implicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0s</td>\n<td headers=\"4789 stub_1_1 missing_implicit_pct\" class=\"gt_row gt_right\">0.0%</td>\n<td headers=\"4789 stub_1_1 missing_explicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0s</td>\n<td headers=\"4789 stub_1_1 missing_explicit_pct\" class=\"gt_row gt_right\">0.0%</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"14\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"5541\">5541</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"5541 stub_1_2 available_data\" class=\"gt_row gt_center\">2h 37m</td>\n<td headers=\"5541 stub_1_2 available_data_pct\" class=\"gt_row gt_right\">100.0%</td>\n<td headers=\"5541 stub_1_2 number_irregulars\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"5541 stub_1_2 total_duration\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">2h 37m</td>\n<td headers=\"5541 stub_1_2 interval\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">60s (~1 minutes)</td>\n<td headers=\"5541 stub_1_2 number_gaps\" class=\"gt_row gt_right\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0</td>\n<td headers=\"5541 stub_1_2 mean_gap_duration\" class=\"gt_row gt_right\">0s</td>\n<td headers=\"5541 stub_1_2 missing_data\" class=\"gt_row gt_center\">0s</td>\n<td headers=\"5541 stub_1_2 missing_data_pct\" class=\"gt_row gt_right\">0.0%</td>\n<td headers=\"5541 stub_1_2 missing_implicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0s</td>\n<td headers=\"5541 stub_1_2 missing_implicit_pct\" class=\"gt_row gt_right\">0.0%</td>\n<td headers=\"5541 stub_1_2 missing_explicit\" class=\"gt_row gt_center\" style=\"border-left-width: 1px; border-left-style: solid; border-left-color: grey80;\">0s</td>\n<td headers=\"5541 stub_1_2 missing_explicit_pct\" class=\"gt_row gt_right\">0.0%</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"14\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> If n &gt; 0: it is possible that the other summary statistics are affected, as they are calculated based on the most prominent interval.</td>\n    </tr>\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"14\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span> Number of (missing or actual) observations</td>\n    </tr>\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"14\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>3</sup></span> Based on times, not necessarily number of observations</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n1. As we have less than one day of data, it would not be sensible to check for missing data with regards to a full day.\n2. Hides a few columns which are unnecessary here\n\n### Logs\n\nParticipant logs are stored in a consolidated Excel file. @fig-log shows the contents of the files when opened in Excel. \n\n::: {.callout-note}\n#### On pre-cleaning of manually entered content (logs/diaries)\n\nNote that pre-cleaning was performed to ensure consistent naming and formatting. I have yet to come upon an experiment with manually entered content in the form of logs or diaries that required no cleaning whatsoever. \n\nThe utility of these data depend heavily on these factors, some of which can be changed after import:\n\n- Identical naming of grouping variables between wearable devices and logs. If there are even slight differences, like an additional whitespace \" \", the merge will be lossy.\n\n- Date, time, and datetime formats must be absolutely consistent and follow a standard formatting convention. If there are differences, they will be read in as text and parsing whole columns to the desired format can be lossy.\n:::\n\n::: {.column-margin}\n![Participant log as opened in Excel](assets/advanced/light_therapy_log.png){#fig-log}\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\npath <- \"data/light_therapy/event_log_LightLamp.xlsx\"\nstate_data <- read_excel(path)\nstate_data |> group_by(Participant) |>  slice_head(n=2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n# Groups:   Participant [2]\n  Participant Event    type  Date                Time               \n        <dbl> <chr>    <chr> <dttm>              <dttm>             \n1        4789 baseline start 2025-10-30 00:00:00 1899-12-31 09:47:00\n2        4789 baseline end   2025-10-30 00:00:00 1899-12-31 09:48:00\n3        5541 baseline start 2025-10-30 00:00:00 1899-12-31 09:47:00\n4        5541 baseline end   2025-10-30 00:00:00 1899-12-31 09:48:00\n```\n\n\n:::\n:::\n\n\nNext we need to make adjustments to naming and types of variables. Note that the time variable is already recognized as a datetime, but with a nonsensical date.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstate_data <-\n  state_data |> \n    rename(Id = Participant, state = Event) |> #<1>\n    mutate(Datetime = `date<-`(Time, Date), #<2>\n           Id = factor(Id)) |> #<2>\n    select(-Date, -Time) |> #<2>\n    number_states(type, use.original.state = FALSE) |> #<3>\n    pivot_wider(id_cols = c(Id, state, type.count), values_from = Datetime, #<4>\n                names_from = type) |> #<4>\n    select(-type.count) |> \n  group_by(Id)\n```\n:::\n\n\n1. Use naming conventions from `LightLogR`\n2. Create a datetime that takes the `Time` variable (which is already recognized as a datetime) and just replace the `Date` component. `Id` is changed to a factor, and unnecessary columns are dropped\n3. Number the `type` column by increasing the number with each `start` and `end` combo.\n4. Pivot the dataset so that we end up with a `start` and `end` datetime for each state.\n\nLet's get an overview of our states before merging.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstate_data |> \n  gt(rowname_col = \"state\") |> \n  tab_footnote(\n    (\"Note that only ID 5541 received the therapy light intervention, \n     but the time span it was active in the room is denoted in both \n     state datasets\"), \n    locations = cells_stub(contains(\"therapy light\"))\n    )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"kkdoksgysp\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#kkdoksgysp table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#kkdoksgysp thead, #kkdoksgysp tbody, #kkdoksgysp tfoot, #kkdoksgysp tr, #kkdoksgysp td, #kkdoksgysp th {\n  border-style: none;\n}\n\n#kkdoksgysp p {\n  margin: 0;\n  padding: 0;\n}\n\n#kkdoksgysp .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#kkdoksgysp .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#kkdoksgysp .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#kkdoksgysp .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#kkdoksgysp .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kkdoksgysp .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kkdoksgysp .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kkdoksgysp .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#kkdoksgysp .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#kkdoksgysp .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#kkdoksgysp .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#kkdoksgysp .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#kkdoksgysp .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#kkdoksgysp .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#kkdoksgysp .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#kkdoksgysp .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#kkdoksgysp .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#kkdoksgysp .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#kkdoksgysp .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kkdoksgysp .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#kkdoksgysp .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#kkdoksgysp .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#kkdoksgysp .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kkdoksgysp .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#kkdoksgysp .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#kkdoksgysp .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kkdoksgysp .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kkdoksgysp .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#kkdoksgysp .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kkdoksgysp .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#kkdoksgysp .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kkdoksgysp .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kkdoksgysp .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kkdoksgysp .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kkdoksgysp .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kkdoksgysp .gt_left {\n  text-align: left;\n}\n\n#kkdoksgysp .gt_center {\n  text-align: center;\n}\n\n#kkdoksgysp .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#kkdoksgysp .gt_font_normal {\n  font-weight: normal;\n}\n\n#kkdoksgysp .gt_font_bold {\n  font-weight: bold;\n}\n\n#kkdoksgysp .gt_font_italic {\n  font-style: italic;\n}\n\n#kkdoksgysp .gt_super {\n  font-size: 65%;\n}\n\n#kkdoksgysp .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#kkdoksgysp .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#kkdoksgysp .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#kkdoksgysp .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#kkdoksgysp .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#kkdoksgysp .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#kkdoksgysp .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#kkdoksgysp .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#kkdoksgysp div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"start\">start</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"end\">end</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"3\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"4789\">4789</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\">baseline</th>\n<td headers=\"4789 stub_1_1 start\" class=\"gt_row gt_right\">2025-10-30 09:47:00</td>\n<td headers=\"4789 stub_1_1 end\" class=\"gt_row gt_right\">2025-10-30 09:48:00</td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_left gt_stub\">pre-light</th>\n<td headers=\"4789 stub_1_2 start\" class=\"gt_row gt_right\">2025-10-30 09:48:00</td>\n<td headers=\"4789 stub_1_2 end\" class=\"gt_row gt_right\">2025-10-30 10:34:00</td></tr>\n    <tr><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_left gt_stub\">therapy light<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n<td headers=\"4789 stub_1_3 start\" class=\"gt_row gt_right\">2025-10-30 10:34:00</td>\n<td headers=\"4789 stub_1_3 end\" class=\"gt_row gt_right\">2025-10-30 10:36:00</td></tr>\n    <tr><th id=\"stub_1_4\" scope=\"row\" class=\"gt_row gt_left gt_stub\">toilet</th>\n<td headers=\"4789 stub_1_4 start\" class=\"gt_row gt_right\">2025-10-30 10:36:00</td>\n<td headers=\"4789 stub_1_4 end\" class=\"gt_row gt_right\">2025-10-30 10:41:00</td></tr>\n    <tr><th id=\"stub_1_5\" scope=\"row\" class=\"gt_row gt_left gt_stub\">therapy light<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n<td headers=\"4789 stub_1_5 start\" class=\"gt_row gt_right\">2025-10-30 10:41:00</td>\n<td headers=\"4789 stub_1_5 end\" class=\"gt_row gt_right\">2025-10-30 11:35:00</td></tr>\n    <tr><th id=\"stub_1_6\" scope=\"row\" class=\"gt_row gt_left gt_stub\">post-light</th>\n<td headers=\"4789 stub_1_6 start\" class=\"gt_row gt_right\">2025-10-30 11:35:00</td>\n<td headers=\"4789 stub_1_6 end\" class=\"gt_row gt_right\">2025-10-30 12:20:00</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"3\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"5541\">5541</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_7\" scope=\"row\" class=\"gt_row gt_left gt_stub\">baseline</th>\n<td headers=\"5541 stub_1_7 start\" class=\"gt_row gt_right\">2025-10-30 09:47:00</td>\n<td headers=\"5541 stub_1_7 end\" class=\"gt_row gt_right\">2025-10-30 09:48:00</td></tr>\n    <tr><th id=\"stub_1_8\" scope=\"row\" class=\"gt_row gt_left gt_stub\">pre-light</th>\n<td headers=\"5541 stub_1_8 start\" class=\"gt_row gt_right\">2025-10-30 09:48:00</td>\n<td headers=\"5541 stub_1_8 end\" class=\"gt_row gt_right\">2025-10-30 10:34:00</td></tr>\n    <tr><th id=\"stub_1_9\" scope=\"row\" class=\"gt_row gt_left gt_stub\">therapy light<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n<td headers=\"5541 stub_1_9 start\" class=\"gt_row gt_right\">2025-10-30 10:34:00</td>\n<td headers=\"5541 stub_1_9 end\" class=\"gt_row gt_right\">2025-10-30 11:35:00</td></tr>\n    <tr><th id=\"stub_1_10\" scope=\"row\" class=\"gt_row gt_left gt_stub\">post-light</th>\n<td headers=\"5541 stub_1_10 start\" class=\"gt_row gt_right\">2025-10-30 11:35:00</td>\n<td headers=\"5541 stub_1_10 end\" class=\"gt_row gt_right\">2025-10-30 11:41:00</td></tr>\n    <tr><th id=\"stub_1_11\" scope=\"row\" class=\"gt_row gt_left gt_stub\">put sweater on</th>\n<td headers=\"5541 stub_1_11 start\" class=\"gt_row gt_right\">2025-10-30 11:41:00</td>\n<td headers=\"5541 stub_1_11 end\" class=\"gt_row gt_right\">2025-10-30 11:42:00</td></tr>\n    <tr><th id=\"stub_1_12\" scope=\"row\" class=\"gt_row gt_left gt_stub\">post-light</th>\n<td headers=\"5541 stub_1_12 start\" class=\"gt_row gt_right\">2025-10-30 11:42:00</td>\n<td headers=\"5541 stub_1_12 end\" class=\"gt_row gt_right\">2025-10-30 12:20:00</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"3\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> Note that only ID 5541 received the therapy light intervention, \n     but the time span it was active in the room is denoted in both \n     state datasets</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Combine light and log data\n\nCombining wearable data with state data is very easy, once both datasets have been properly prepared.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# states to keep\nstates_to_keep <- c(\"pre-light\", \"therapy light\", \"post-light\", \"baseline\")\ndata <-\n  data |> \n  select(Id, Datetime, MEDI) |> \n  add_states(state_data, force.tz = TRUE) |> #<1>\n  mutate(state = state |> \n                  factor(levels = states_to_keep, #<2>\n                         labels = states_to_keep |> str_to_sentence()) |> #<2>\n                  fct_recode(`Desk (horizontal)` = \"Baseline\") #<2>\n  )\ndata |> slice_head(n=3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n# Groups:   Id [2]\n  Id    Datetime             MEDI state            \n  <fct> <dttm>              <dbl> <fct>            \n1 4789  2025-10-30 09:46:50  286. <NA>             \n2 4789  2025-10-30 09:47:50  387. Desk (horizontal)\n3 4789  2025-10-30 09:48:50  410. Pre-light        \n4 5541  2025-10-30 09:46:36  279. <NA>             \n5 5541  2025-10-30 09:47:36  331. Desk (horizontal)\n6 5541  2025-10-30 09:48:36  353. Pre-light        \n```\n\n\n:::\n:::\n\n\n1. Merges the `state_data` participant logs with the wearable `data`. `force.tz = TRUE` assures that the times from the states dataset are matched up with the light data, even though the light data uses the `Central European Time`, whereas the states use the default `UTC` time zone.\n2. Here we perform several actions on the resulting state. First, we create a factor that only has the relevant states (and will be `NA` otherwise), and relabel them for sentence case. Lastly we recode the baseline to the correct label.\n\n## Compare conditions\n\n### Histogram\n\nThis next section is not using any `LightLogR` functions, but it helps to get a sense for the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |> \n  filter(state %in% c(\"Post-light\", \"Pre-light\", \"Therapy light\")) |> \n  ggplot(aes(x=MEDI, y = state, fill = fct_rev(Id))) +\n  geom_density_ridges(aes(height = after_stat(ncount)), \n                      stat = \"binline\",\n                      binwidth = 100, \n                      col = NA,\n                      alpha = 0.75,\n                      scale = 0.75,\n                      draw_baseline = TRUE) +\n  theme_ridges() +\n  ggsci::scale_fill_jco() +\n  scale_x_continuous(breaks = c(0, seq(500, 2500, by = 500))) +\n  coord_cartesian(ylim = c(1, NA), expand = FALSE) +\n  labs(y = NULL, x = \"melanopic EDI (lx)\", fill = \"Participant\") +\n  theme(panel.grid.major.y = ggplot2::element_line(\"grey95\"), \n    panel.grid.major.x = ggplot2::element_line(colour = \"grey\", \n      linewidth = 0.25))\n```\n\n::: {.cell-output-display}\n![](advanced_03_light_therapy_files/figure-html/histogram-1.png){width=768}\n:::\n:::\n\n\n### Table\n\nThis section serves to create a fully code-based tabular overview of the data. First, we need to collect the data in the necessary format. Here, one important question arises. Because of the interruptions, no participant has a singular period for all three conditions (pre, light, post). Depending on the `LightLogR` functions we use, we can either calculate key metrics for all times a certain state is active (`by state`), or by each episode a certain state is active (`by episode`). In our case, the `by state` approach is the better one, but we will highlight both workflows here:\n\n::: {.panel-tabset}\n\n#### by episode\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |>\n  extract_states(state) |> #<1>\n  extract_metric(data, #<2>\n                 mean = mean(MEDI), #<2>\n                 dose = dose(MEDI, Datetime, epoch = \"60s\", na.rm = TRUE )) |>  #<2>\n  summarize_numeric() |> #<3>\n  select(Id, state, episodes, mean_mean, mean_dose, total_duration) |> \n  drop_na() \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 6\n# Groups:   Id [2]\n  Id    state             episodes mean_mean mean_dose total_duration     \n  <fct> <fct>                <int>     <dbl>     <dbl> <Duration>         \n1 4789  Pre-light                1      236.    181.   2760s (~46 minutes)\n2 4789  Therapy light            2      251.    125.   3360s (~56 minutes)\n3 4789  Post-light               1      227.    171.   2700s (~45 minutes)\n4 4789  Desk (horizontal)        1      387.      6.45 60s (~1 minutes)   \n5 5541  Pre-light                1      273.    210.   2760s (~46 minutes)\n6 5541  Therapy light            1     2022.   2056.   3660s (~1.02 hours)\n7 5541  Post-light               2      315.    108.   2640s (~44 minutes)\n8 5541  Desk (horizontal)        1      331.      5.52 60s (~1 minutes)   \n```\n\n\n:::\n:::\n\n\n1. Condense the dataset to an account of each episode of state (given the grouping by participant). While this is very close to our original `state_data` it takes the wearable data into account as well.\n2. We extract specific metrics from the original dataset with regards to the extracted data. In this case the arithmetic mean (as logarithmic distribution is not really an issue here), and the dose of light.\n3. This function not only calculates the average of values within each group (participant and state in this case), but also provide the total duration for each condition.\n\nHave a special look at the `dose`. Participant `4789` has an average illuminance of ~250 lx during `Therapy light`, which lasted for a total of 56 minutes. But the dose only shows ~ 125 lx·h. The reason for that is, because it is not `dose`, but the `mean_dose` across all episodes, of which there are two (due to the interruption). We could correct that bei either scaling the dose by episode post-hoc, or by using a manual summary function that takes the duration of individual episodes into account. Instead, we have a different way of getting to the correct outcome by using the `durations()` function instead of `extract_states()`.\n\n#### by state\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_prep <- #<1>\ndata |>\n  drop_na(state) |> \n  group_by(state, .add = TRUE)\n\ndata_prep |> \n  durations(MEDI) |> #<2>\n  extract_metric(data_prep, #<3>\n                 identifying.colname = state, #<4>\n                 mean = mean(MEDI), \n                 dose = dose(MEDI, Datetime, epoch = \"60s\", na.rm = TRUE )) |>\n  select(Id, state, mean, dose, total_duration = duration)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 5\n# Groups:   Id, state [8]\n  Id    state              mean    dose total_duration     \n  <fct> <fct>             <dbl>   <dbl> <Duration>         \n1 4789  Pre-light          236.  181.   2760s (~46 minutes)\n2 4789  Therapy light      267.  249.   3360s (~56 minutes)\n3 4789  Post-light         227.  171.   2700s (~45 minutes)\n4 4789  Desk (horizontal)  387.    6.45 NA                 \n5 5541  Pre-light          273.  210.   2760s (~46 minutes)\n6 5541  Therapy light     2022. 2056.   3660s (~1.02 hours)\n7 5541  Post-light         295.  217.   2640s (~44 minutes)\n8 5541  Desk (horizontal)  331.    5.52 NA                 \n```\n\n\n:::\n:::\n\n\n1. We require a dataset that is also grouped by the state variable\n2. Calculate the duration of every state - but only when a value for melanopic EDI is available \n3. The function requires the same dataset that was the basis for `durations()`.\n4. It further requires an identifying column name for the extraction. In our case, the `state` column is sufficient\n\nAgain, have a look at the `dose`. Participant `4789` has an average illuminance of ~267 lx during `Therapy light`, which lasted for a total of 56 minutes. The dose is 249 lx·h, which is exactly what you would get by dividing 267lx by 60 minutes times 56 minutes.\n\n:::\n\nThus we will continue with the `by state` method and prepare the data for the table\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_tbl_comparison <- \ndata_prep |> \n  durations(MEDI) |> \n  extract_metric(data_prep, \n                 identifying.colname = state, \n                 mean = mean(MEDI), \n                 dose = dose(MEDI, Datetime, epoch = \"60s\", na.rm = TRUE )) |>\n  select(Id, state, mean, dose, total_duration = duration) |> \n  mutate(Id = case_when(  \n                        Id == \"4789\" ~ \"Control condition\", \n                        Id == \"5541\" ~ \"Therapy light\"), \n         across(contains(\"total_duration\"), \\(x) replace_na(x, dminutes(1))) #<1>\n         ) |>\n  pivot_wider(id_cols = state, #<2>\n              names_from = Id, #<2>\n              values_from = c(mean, total_duration, dose)) |> #<2>\n  arrange(state) |> \n  select(1, 2, 4, 6, 3, 5, 7)\n```\n:::\n\n\n1. If there is only a singular datapoint, `durations()` can not discern its *validity* duration. Here we manually exchange it for the epoch.\n2. By pivoting wider we move from one row per condition and participant to one row per condition.\n\nThen we can produce the table. This next code cells does not contain any `LightLogR` functions, but simply uses our previous output (`data_tbl_comparison`) and prints it as a `gt` table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_tbl_comparison |> \n  gt(rowname_col = \"state\", groupname_col = NULL) |> \n  tab_spanner(\"Control condition\", contains(\"Control condition\")) |> \n  tab_spanner(\"Therapy lamp\", contains(\"Therapy light\", ignore.case = FALSE)) |> \n  cols_label_with(\n    fn = \\(x) x |> \n               str_remove_all(\" |_|Control|condition|Therapy|total|light|No\") |> \n               str_to_title()\n    ) |> \n  tab_style(locations = cells_column_spanners(1),\n            style = cell_text(color = \"#EFC000\", weight = \"bold\")\n  ) |> \n  tab_style(locations = cells_column_spanners(2),\n            style = cell_text(color = \"#0073C2\", weight = \"bold\")\n  ) |> \n  cols_align(\"left\", columns = state) |> \n  cols_add(\n    `Rel. difference` = \n    (`dose_Therapy light`-`dose_Control condition`)/`dose_Control condition`) |> \n  fmt(columns = contains(\"mean\"), \n      fns =  \\(x) vec_fmt_number(x, decimals = 0, pattern = \"{x} lx\")\n      ) |> \n  fmt(columns = contains(\"dose\"), \n      fns =  \\(x) vec_fmt_number(x, decimals = 0, pattern = \"{x} lx·h\")\n      ) |> \n  fmt_percent(contains(\"difference\"), force_sign = TRUE, decimals = 0) |> \n  gt::cols_width(-state ~ px(100), \n                 state ~ px(150)) |> \n  grand_summary_rows(\n    columns = contains(\"dose\"),\n    fns = list(label = \"Overall\", id = \"overall\", fn = \"sum\"),\n    fmt = contains(\"dose\")~ fmt_number(., decimals = 0, pattern = \"{x} lx·h\")\n  ) |> \n  grand_summary_rows(\n    columns = contains(\"duration\"),\n    fns = list(label = \"Overall\", id = \"overall\", fn = \"sum\"),\n    missing_text = \"\",\n    fmt = ~ fmt_duration(., input_units = \"seconds\", output_units = \"minutes\",\n                         duration_style = \"wide\"),\n  ) |> \n  gt::grand_summary_rows(\n    fns = list(label = \"Overall\", id = \"totals\") ~ \n      (sum(`dose_Therapy light`)/sum(`dose_Control condition`)-1),\n    fmt = ~ gt::fmt_percent(., decimals = 0, force_sign = TRUE),\n    columns = dplyr::contains(\"difference\"),\n    missing_text = \"\"\n    ) |> \n  fmt_duration(contains(\"duration\"), \n               input_units = \"seconds\", \n               output_units = \"minutes\",\n               duration_style = \"wide\") |> \n  tab_style(locations = list(cells_stub(), \n                             cells_column_labels(),\n                             cells_stub_grand_summary()),\n            style = cell_text(weight = \"bold\"))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"kipjkhnysg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#kipjkhnysg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#kipjkhnysg thead, #kipjkhnysg tbody, #kipjkhnysg tfoot, #kipjkhnysg tr, #kipjkhnysg td, #kipjkhnysg th {\n  border-style: none;\n}\n\n#kipjkhnysg p {\n  margin: 0;\n  padding: 0;\n}\n\n#kipjkhnysg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#kipjkhnysg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#kipjkhnysg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#kipjkhnysg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#kipjkhnysg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kipjkhnysg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kipjkhnysg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kipjkhnysg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#kipjkhnysg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#kipjkhnysg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#kipjkhnysg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#kipjkhnysg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#kipjkhnysg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#kipjkhnysg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#kipjkhnysg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#kipjkhnysg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#kipjkhnysg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#kipjkhnysg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#kipjkhnysg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kipjkhnysg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#kipjkhnysg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#kipjkhnysg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#kipjkhnysg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kipjkhnysg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#kipjkhnysg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#kipjkhnysg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kipjkhnysg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kipjkhnysg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#kipjkhnysg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kipjkhnysg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#kipjkhnysg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kipjkhnysg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kipjkhnysg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kipjkhnysg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kipjkhnysg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kipjkhnysg .gt_left {\n  text-align: left;\n}\n\n#kipjkhnysg .gt_center {\n  text-align: center;\n}\n\n#kipjkhnysg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#kipjkhnysg .gt_font_normal {\n  font-weight: normal;\n}\n\n#kipjkhnysg .gt_font_bold {\n  font-weight: bold;\n}\n\n#kipjkhnysg .gt_font_italic {\n  font-style: italic;\n}\n\n#kipjkhnysg .gt_super {\n  font-size: 65%;\n}\n\n#kipjkhnysg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#kipjkhnysg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#kipjkhnysg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#kipjkhnysg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#kipjkhnysg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#kipjkhnysg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#kipjkhnysg .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#kipjkhnysg .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#kipjkhnysg div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" style=\"table-layout:fixed;width:0px;\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <colgroup>\n    <col style=\"width:150px;\"/>\n    <col style=\"width:100px;\"/>\n    <col style=\"width:100px;\"/>\n    <col style=\"width:100px;\"/>\n    <col style=\"width:100px;\"/>\n    <col style=\"width:100px;\"/>\n    <col style=\"width:100px;\"/>\n    <col style=\"width:100px;\"/>\n  </colgroup>\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" style=\"color: #EFC000; font-weight: bold;\" scope=\"colgroup\" id=\"Control condition\">\n        <div class=\"gt_column_spanner\">Control condition</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" style=\"color: #0073C2; font-weight: bold;\" scope=\"colgroup\" id=\"Therapy lamp\">\n        <div class=\"gt_column_spanner\">Therapy lamp</div>\n      </th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"2\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Rel.-difference\">Rel. difference</th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"mean_Control-condition\">Mean</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"total_duration_Control-condition\">Duration</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"dose_Control-condition\">Dose</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"mean_Therapy-light\">Mean</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"total_duration_Therapy-light\">Duration</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"dose_Therapy-light\">Dose</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\" style=\"font-weight: bold;\">Pre-light</th>\n<td headers=\"stub_1_1 mean_Control condition\" class=\"gt_row gt_right\">236 lx</td>\n<td headers=\"stub_1_1 total_duration_Control condition\" class=\"gt_row gt_center\">46 minutes</td>\n<td headers=\"stub_1_1 dose_Control condition\" class=\"gt_row gt_right\">181 lx·h</td>\n<td headers=\"stub_1_1 mean_Therapy light\" class=\"gt_row gt_right\">273 lx</td>\n<td headers=\"stub_1_1 total_duration_Therapy light\" class=\"gt_row gt_center\">46 minutes</td>\n<td headers=\"stub_1_1 dose_Therapy light\" class=\"gt_row gt_right\">210 lx·h</td>\n<td headers=\"stub_1_1 Rel. difference\" class=\"gt_row gt_right\">+16%</td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_left gt_stub\" style=\"font-weight: bold;\">Therapy light</th>\n<td headers=\"stub_1_2 mean_Control condition\" class=\"gt_row gt_right\">267 lx</td>\n<td headers=\"stub_1_2 total_duration_Control condition\" class=\"gt_row gt_center\">56 minutes</td>\n<td headers=\"stub_1_2 dose_Control condition\" class=\"gt_row gt_right\">249 lx·h</td>\n<td headers=\"stub_1_2 mean_Therapy light\" class=\"gt_row gt_right\">2,022 lx</td>\n<td headers=\"stub_1_2 total_duration_Therapy light\" class=\"gt_row gt_center\">61 minutes</td>\n<td headers=\"stub_1_2 dose_Therapy light\" class=\"gt_row gt_right\">2,056 lx·h</td>\n<td headers=\"stub_1_2 Rel. difference\" class=\"gt_row gt_right\">+725%</td></tr>\n    <tr><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_left gt_stub\" style=\"font-weight: bold;\">Post-light</th>\n<td headers=\"stub_1_3 mean_Control condition\" class=\"gt_row gt_right\">227 lx</td>\n<td headers=\"stub_1_3 total_duration_Control condition\" class=\"gt_row gt_center\">45 minutes</td>\n<td headers=\"stub_1_3 dose_Control condition\" class=\"gt_row gt_right\">171 lx·h</td>\n<td headers=\"stub_1_3 mean_Therapy light\" class=\"gt_row gt_right\">295 lx</td>\n<td headers=\"stub_1_3 total_duration_Therapy light\" class=\"gt_row gt_center\">44 minutes</td>\n<td headers=\"stub_1_3 dose_Therapy light\" class=\"gt_row gt_right\">217 lx·h</td>\n<td headers=\"stub_1_3 Rel. difference\" class=\"gt_row gt_right\">+27%</td></tr>\n    <tr><th id=\"stub_1_4\" scope=\"row\" class=\"gt_row gt_left gt_stub\" style=\"font-weight: bold;\">Desk (horizontal)</th>\n<td headers=\"stub_1_4 mean_Control condition\" class=\"gt_row gt_right\">387 lx</td>\n<td headers=\"stub_1_4 total_duration_Control condition\" class=\"gt_row gt_center\">1 minute</td>\n<td headers=\"stub_1_4 dose_Control condition\" class=\"gt_row gt_right\">6 lx·h</td>\n<td headers=\"stub_1_4 mean_Therapy light\" class=\"gt_row gt_right\">331 lx</td>\n<td headers=\"stub_1_4 total_duration_Therapy light\" class=\"gt_row gt_center\">1 minute</td>\n<td headers=\"stub_1_4 dose_Therapy light\" class=\"gt_row gt_right\">6 lx·h</td>\n<td headers=\"stub_1_4 Rel. difference\" class=\"gt_row gt_right\">−14%</td></tr>\n    <tr><th id=\"grand_summary_stub_1\" scope=\"row\" class=\"gt_row gt_left gt_stub gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\" style=\"font-weight: bold;\">Overall</th>\n<td headers=\"grand_summary_stub_1 mean_Control condition\" class=\"gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\"><br /></td>\n<td headers=\"grand_summary_stub_1 total_duration_Control condition\" class=\"gt_row gt_center gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">148 minutes</td>\n<td headers=\"grand_summary_stub_1 dose_Control condition\" class=\"gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">607 lx·h</td>\n<td headers=\"grand_summary_stub_1 mean_Therapy light\" class=\"gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\"><br /></td>\n<td headers=\"grand_summary_stub_1 total_duration_Therapy light\" class=\"gt_row gt_center gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">152 minutes</td>\n<td headers=\"grand_summary_stub_1 dose_Therapy light\" class=\"gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">2,487 lx·h</td>\n<td headers=\"grand_summary_stub_1 Rel. difference\" class=\"gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">+310%</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n### Plot\n\nIn this section we create two plots of our data, highlighting the differences due to the intervention. The first plot contains a timeline of melanopic EDI, the second the cumulative dose. \n\nWe start with a few necessary preparations:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# times set the experimental states\ntimes <- c(9 +48/60, 10 + 34/60, 11 + 35/60, 12 + 20/60)*60*60\n\n# define a protocol axis for plotting\nprotocol_bracket <- primitive_bracket(\n  # Keys determine what is displayed\n  key = key_range_manual(start = times[1:3], end = times[2:4], level = 1,\n                         name = c(\"Pre-light\", \"Therapy light\", \"Post-light\")),\n  bracket = \"square\",\n  theme = theme(legend.text = element_text(face = \"bold\"))\n)\n\n#paths to symbols\npath_lamp <- \"assets/advanced/5541.png\"\npath_default <- \"assets/advanced/4789.png\"\n\n#get relevant data for plotting the symbols\nsymbols <- \ndata |> \n  drop_na(state) |> \n  summarize(\n    dose(MEDI, Datetime, na.rm = TRUE, as.df = TRUE),\n    total_duration = n()*60\n  ) |> \n  tibble(\n    image = c(path_default, path_lamp),\n    y = c(600, 2500),\n    x = c(11.125*60*60)\n  )\n```\n:::\n\n\nNow we are ready to create the first plot:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |> \n  drop_na(state) |> #<1>\n  filter(state != \"Desk (horizontal)\") |> #<1>\n  gap_handler() |> #<2>\n  gg_day(aes_col = fct_rev(Id), #<3>\n         geom = \"line\", #<4>\n         facetting = FALSE, #<5>\n         y.scale = \"identity\", #<6>\n         x.axis.breaks = hms::hms(hours = seq(0, 24, by = 0.5)), #<7>\n         y.axis.breaks = c(0, 250,seq(500, 2500, by = 500))) |> #<8>\n  gg_states(state, #<9>\n            aes_fill = state, #<9>\n            alpha = 0.05, #<9> \n            ) + #<9>\n  scale_fill_manual(values = c(`Therapy light` = \"#0073C2FF\")) + #<10>\n  guides(fill = \"none\", color = \"none\", \n         x = guide_axis_stack(protocol_bracket, \"axis\")) + #<11>\n  coord_cartesian(xlim = c(9.5, 12.6)*60*60, #<12>\n                  ylim = c(0, 2850), \n                  expand = FALSE) +\n  geom_image(data = symbols, inherit.aes = FALSE, #<13>\n             aes(image = image, x = x, y = y), size = 0.2, alpha = 1) +\n  labs(caption = \n         \"Note: interruptions from the protocol (e.g. restroom usage) were removed.\"\n       )\n```\n\n::: {.cell-output-display}\n![](advanced_03_light_therapy_files/figure-html/medi plot-1.png){width=672}\n:::\n:::\n\n\n1. Remove all the states that do not belong the experimental protocol\n2. Fill in empty observations for the filtered times\n3. `LightLogR` plotting function - we use the reverse coding of participants to get the desired coloring\n4. By default `gg_day()` plots points, this changes it to lines\n5. By default, `gg_day()` creates one panel per day. In this case, we are not interested in identifying the day.\n6. By default, `gg_day()` scales with `symlog` to include 0 with logarithmic scaling. `\"identity\"` simply sets it to a linear scale.\n7. By default, `gg_day()` creates breaks every three hours, here we set it to every half hour.\n8. By default, `gg_day()` sets breaks every 10^ step. Here we set it to steps of 500 lx, but also keeping 250 lx, as that is the base intensity.\n9. `gg_states()` adds the backdrop of states. Try setting `ymin` and `ymax`.\n10. Ensures that the `Therapy light` condition has a blue coloring\n11. Adds the axis we prepared before\n12. Reduce the limits of the plots to areas of interest\n13. Adding the symbols\n\nLastly, we create a cumulative plot. Only the differences compared to above will be highlighted here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |> \n  drop_na(state) |>\n  filter(state != \"Desk (horizontal)\") |> \n  mutate(\n    dose = cumsum(MEDI)/60 #<1>\n  ) |> \n  gap_handler() |>\n  gg_day(aes_col = fct_rev(Id), geom = \"line\", facetting = FALSE,\n         y.axis = dose, #<2>\n         y.scale = \"identity\",\n         x.axis.breaks = hms::hms(hours = seq(0, 24, by = 0.5)),\n         y.axis.breaks = c(seq(0, 2500, by = 500))\n         ) |> \n  gg_states(state, aes_fill = state, alpha = 0.05) +\n  scale_fill_manual(values = c(`Therapy light` = \"#0073C2FF\")) +\n  guides(fill = \"none\", color = \"none\", \n         x = guide_axis_stack(protocol_bracket, \"axis\")) +\n  coord_cartesian(xlim = c(9.5, 12.6)*60*60, \n                  ylim = c(0, 2850),\n                  expand = FALSE,\n                  clip = FALSE\n                  ) +\n  geom_image(data = symbols, inherit.aes = FALSE,\n             aes(image = image,\n                 x = 12.48*60*60,\n                 y = dose),\n             size = 0.15\n             ) +\n  labs(\n    caption = \n      \"Note: interruptions from the protocol (e.g. restroom usage) were removed.\"\n    )\n```\n\n::: {.cell-output-display}\n![](advanced_03_light_therapy_files/figure-html/cumulative plot-1.png){width=672}\n:::\n:::\n\n\n1. We calculate a cumulative value from start to end for each participant\n2. We set the y.axis variable to `dose` instead of the default `MEDI`\n\n## Conclusion\n\nCongratulations! You have finished this section of the advanced course. If you go back to the [homepage](index.qmd), you can select one of the other use cases.\n\n",
    "supporting": [
      "advanced_03_light_therapy_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}